rpmem: switch to using an open coded basename
On FreeBSD, clang fails with the error:

> rpmemd_log.c:199:26: error: passing 'const char *' to parameter of type 'char *' discards qualifiers
>   [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
>     "[%s:%d] ", basename(fname), lineno);
>                          ^~~~~

Which is right, in fact posix states, "The basename() function may
modify the string pointed to by path..." And FreeBSD's basename(3)
does do such in-place modification.

In practice, any runtime string manipulation can be avoided by
moving the basename logic into a small inline function and letting
the compiler's constant propagation handle the rest.